// Uniqueness Constraints
// Auto-generated by Mapping Engine

CREATE CONSTRAINT zipcode_zipcode IF NOT EXISTS
FOR (n:Zipcode)
REQUIRE n.zipcode IS UNIQUE;

CREATE CONSTRAINT building_bbl IF NOT EXISTS
FOR (n:Building)
REQUIRE n.bbl IS UNIQUE;

CREATE CONSTRAINT housingproject_project_id IF NOT EXISTS
FOR (n:HousingProject)
REQUIRE n.project_id IS UNIQUE;

