// Indexes
// Auto-generated by Mapping Engine

CREATE INDEX zipcode_zipcode IF NOT EXISTS
FOR (n:Zipcode)
ON (n.zipcode);

CREATE INDEX zipcode_borough IF NOT EXISTS
FOR (n:Zipcode)
ON (n.borough);

CREATE INDEX building_zipcode IF NOT EXISTS
FOR (n:Building)
ON (n.zipcode);

CREATE INDEX housingproject_project_name IF NOT EXISTS
FOR (n:HousingProject)
ON (n.project_name);

CREATE INDEX housingproject_postcode IF NOT EXISTS
FOR (n:HousingProject)
ON (n.postcode);

